### ISSUE TITLE
Nice 

### ISSUE THREAD

**Issue by ken-okabe** [fable-compiler/Fable.Solid#1]
Thanks for your great work! @alfonsogarciacaro 

Actually, I was thinking of suggesting migrating to esbuild/vite for Fable projects because the slow old-fashioned Webpack prevailed.
This is so nice.
I also wish the new Fable4 template will be provided with vite. Thanks.

**Comment by alfonsogarciacaro** [comment]
Thanks for the nice words @stken2050! Yes, I'm mostly using Vite for new projects because it needs less config than Webpack and works quite well. It's a good idea to use it for the templates when we upgrade them to Fable 4 as you say 👍
