### ISSUE TITLE
Missing SolidJS component - `ErrorBoundary`

### ISSUE THREAD

**Issue by semuserable** [fable-compiler/Fable.Solid#11]
https://www.solidjs.com/tutorial/flow_error_boundary

```typescript
<ErrorBoundary fallback={err => err}>
  <Broken />
</ErrorBoundary>
```

**Comment by alfonsogarciacaro** [comment]
It shouldn't be too difficult to add this and the other APIs you asked for. I'll try to do it over the weekend 👍

**Comment by semuserable** [comment]
Thank you very much @alfonsogarciacaro!

As an example, I thought about something like this

```fsharp
type Solid =
  [<ImportMember("solid-js"); JSX.Component>]
  static member ErrorBoundary(fallback: JSX.Element, children: JSX.Element): JSX.Element = jsNative
```

But it covers only one flow for `fallback`. I guess I should be using `U2` to cover TypeScript OR type definition, but I don't know for sure. Also, original TypeScript definition returns `Accessor<JSX.Element>` and if I interop that it won't work as `JSX.Element` is expected. I checked how you did it for `Switch` which also returns `Accessor<JSX.Element>` and tried the same here.

**Comment by alfonsogarciacaro** [comment]
Yes, covering all the possibilities is tricky because Solid API is very dynamic. I'm trying to cover the (I hope) 90% of use cases when interacting and prioritize making a nice F# API.

`U2` types are not veery ergonomic and I try to avoid them when possible. In this case you can use an overload or just `fallback: JSX.ElementType` which at the end is `obj` so it accepts anything.

**Comment by obeavers** [comment]
Hey @alfonsogarciacaro, is this something you've had a chance to take a stab at?

**Comment by alfonsogarciacaro** [comment]
Hi there! Sorry, there were some issues with Fable and dotnet 7 and had to fix those first.

I've published a new version with ErrorBoundary, context and createRoot. There are examples for the first two in the sample app Counter page. I haven't tested createRoot but hopefully it should work.

When a curried function from a binding receives another function as argument, this causes problems with Fable uncurrying feature in some APIs I have to use System.Action. In those cases, please use .Invoke() to call them.

**Comment by obeavers** [comment]
Thank you!
